### ISSUE TITLE
新エピック武器スキル (pre-research for new epic weapon skills)

### ISSUE THREAD

**Issue by kei-gbf** [MotocalDevelopers/motocal#326]
新エピックウェポンのスキルの先行調査です

- [x] エピックブランド・ゲイン
  - __エピックウェポンの数__ に応じて攻撃UP
- [x] レゾナンス・スタッフ
  - 杖の数に応じて連撃率UP
- [x] ヒロイック・テイル
  - 全ての __武器種__ が異なる時
- [x] ソール・イコーリティ
  - 全ての __武器__ が異なる時

スキル実装の為に必要になりそうな関数のみ実装してみました
https://codepen.io/anon/pen/oKGKyB?editors=0011

その上で、見つかった課題は以下の通り。

### 課題1: エピック武器の識別方法
提案: series: "epic" 項目の導入

- 古いセーブデータでのエピック武器の判別は、
  終末武器で取ったように名前で判別もする。
- メジャーバージョンアップで（現状予定はありませんが、もしあれば）
  名前でチェック方式は取りやめる。(段階を踏んで、古い仕様を排除)
- __追記:__ 他属性は含まれるか。
- __変更:__ category -> series

### 課題2: 全ての武器が異なる時の判別基準

- (要検証情報)
  - [x] オメガ武器やジョブ武器の色変えは、別武器扱いされるか
  - [x] コスモス武器のタイプ違い等も同様
- [ ] (Motocalでの問題) 同一武器を複数の項目に入れた場合の判別方法
  - プラスやスキルレベル、凸状況の異なる武器の区別

----

This is early pre-research topic,
summer 2019 stream announced new epic weapons update.
(not sure the schedule when update)

- "grand epic" (fire/wind/light)
  - [x] isEpicWeapon
- "stuff resonance" (water)
  - [x] count number of wand
- "heroic tale" (earth)
  - when all weapon types are different
    (Director answered on live stream, it works with Kaimu together)
- "absolute equality" (dark)
  - when all weapons are different

NOTICE: "soul equality" same condition with kaimu,
         but "hiroic tale" text seem more strict "weapon type (armType)".

Of course, we does not know details they are not implemented yet.
it's just pre-research, guessed from the skill's text.
we should wait verification details, I just think this snippet can be the start base code.

I've tried to implement functions which may be used in those new skill
https://codepen.io/anon/pen/oKGKyB?editors=0011
(everyone can fork/edit without login, feel free to modify/feedback)

then found issues following:

----
## How to detect Epic Weapon

- [x] New weapons can have new field such like series: "epic"
- [ ] Issue: Old weapon and old save data compatibility, 
      we may need to detect from weapon names, like Opus weapons.
- [x] __EDIT__ does it include other element's Epic ?

__EDIT__ category -> series
__EDIT__ update English skill names

### suggestion:

- [x] Add series field for old/new epic weapons
  - [ ] Add series: "opus" for opus weapons, can be related.
- [ ] isEpicWeapon will double check in the early implementation
  - [x] Check series is "epic"
  - [ ] Check weapon names for Old weapon's backward compatibility 
- [ ] In Major update timing (I don't know, we had not plan this, far future)
  - [ ] drop the old naming check code (at the time when no need to support old data)
  - this will's require long running scheduling road-map, I don't know who can manage this.
    for now, it's just sharing the idea.

## Definition of the unique

- [x] Omega, JMP, different colors are treated as different weapon?
- [x] Cosmos different types, as well.

Kaimu has similar or same support ability, that can be hints to guess the condition
but not sure the same logic is used or not.
This is for check points for verification.

Implementation Issues for Motocal

- [ ] How can we detect that add same weapon as different items.
  - e.g. the weapon with different Lv, plus bonus etc
- [x] ★3/★4 same weapon? but internally data different.

----

TODO: Add source information link, any site made the summary? or wait official announce.

**Comment by kagekiyo7** [comment]
武器種の取得方法としては、txtに記載されているのでそこからできそうですね。武器テンプレートのフィルター機能にも使えそう。
`|&attachref(img/1040307100.png,15%);|ヘルマニビス|&color(#800080){闇};|斧|60|[[死罪の計量>武器奥義#shizainokeiryou]]|[[憎悪の神威>スキル一覧#zouonokamui]]|[[イクシード・ダーク>スキル一覧#limitbreakdark]]|25|415|174|2463|アヌビス討伐戦|ハイグレード武器||`

>同一武器を複数の項目に入れた場合の判別方法

簡単な方法としては、判別するときに名前から「Lv.X」「SLv.X」「+X」の部分を取り除くとかですかね？(そのような名前の武器がないか検査が必要)

そして、現状レベル・スキル・プラスは武器選択時に適応されてしまいますが、それらを武器のパラメータとして与えるように仕様変更するのが理想的な形かなと(後から変更する際にも便利)
パラメータ化して表示の際だけ「武器名+Lv+Slv+プラス」の形にできれば機能的にも今と変わらなそうです。

**Comment by kei-gbf** [comment]
:+1: 
> 現状レベル・スキル・プラスは武器選択時に適応されてしまいますが、それらを武器のパラメータとして与えるように仕様変更するのが理想的な形かなと(後から変更する際にも便利)
パラメータ化して表示の際だけ「武器名+Lv+Slv+プラス」の形にできれば機能的にも今と変わらなそうです。

凸状況や属性変え等、他の要因については要検証として、
後方互換で問題なければ、プラス等をパラメーター化する方式がベストですね。
アップデートとは別で、独立して実装してもよさそうです。

----
エピック武器の識別方法に関しては、
新規追加分に関しては独自のフィールドを持てる為、問題ないのですが、

課題は、過去のセーブデータにどう対応するか。
現状、終末武器で行ったような名前でチェックしか案がありません。

**Comment by kei-gbf** [comment]
I got the first drop, skill2 was on 4★
![キャプチャ](https://user-images.githubusercontent.com/45387555/62522856-81321580-b86d-11e9-94e2-1a458b8c4fba.PNG)

**Comment by kagekiyo7** [comment]
> 『支配の天秤4凸性能検証』※アヌビス杖
> ◆スキル2
> 「装備している武器が全て異なる時」
> ・EX攻刃20%UP(EX攻刃枠加算)
> ・ダメージ上限10%UP

https://twitter.com/Granblue_GW/status/1158739721482199040

- ダメージ上限の枠はどうなのか
- 属性の指定はされていない

----
聖域の錫杖(水)

> 雑に杖1本あたりDA2%、TA1％ってとこかなぁ？うーんしょぼい

https://twitter.com/desuko008/status/1158815266295312385

**Comment by kei-gbf** [comment]
- [ ] スパルタの基礎連撃率 (6.5%? or 7.0%?) 要確認 global_const.js は 7%
- [ ] MB, LB の関与

----

> ダメージ上限の枠はどうなのか

各枠のリストアップ

- [ ] 個人バフ "damageLimit"
- [ ] パーティバフ "damageLimitBuff"
- [ ] 武器スキル枠(上限20%) "normalDamageLimit"
  - [ ] 四象武器邪
  - [ ] オメガ/終末 スキル 通常上限
- [ ] 天司石 (totalSummon["damageLimit"])
- [ ] 至極の指輪 (EXLB WED)

Motocal の現在の実装
```js
// Damage limit UP = Overall buff + Personal buff + skill
var damageLimit = buff["damageLimit"];
damageLimit += totals[key]["damageLimitBuff"];
damageLimit += Math.min(0.20, totals[key]["normalDamageLimit"]);
damageLimit += 0.01 * totalSummon["damageLimit"];
if (totals[key]["EXLB"]["WED"]) {
    damageLimit += 0.05;
}
```

場合によっては #196 で保留になってた、オメガ通常上限と麒麟弓や四象邪枠の
枠上限の判別にも使えそうですね。

**Comment by kagekiyo7** [comment]
>スパルタの基礎連撃率
>MB, LB の関与

DA7%TA3%ですね、それを考慮するとDA11.4%、TA6.6％でDA2%TA1%
ですが、MBLBはどうなっているのかわからないので他に検証データがなかったときの暫定値にしましょう。

----
### エピックブランド・ゲイン (火風光)

> エピックブランド・ゲイン：装備している「エピックウェポン」の数が多いほど攻撃UP（1本につきEX枠4%、最大40%）
> ※このスキル効果が複数重複して発揮されるかは未確認

http://gbf-verification.blog.jp/archives/20260847.html

スキル3つ重複の際

> エピックブランド・ゲインの効果量上限は80％かも

https://twitter.com/mo_gati/status/1159282894122053632

**Comment by kei-gbf** [comment]
３本目で効果は微増するけど上限に引っかかるような配分が多そうですよね。

----
レゾナンス･スタッフ 第２スキル 要検証項目

- [ ] 複数本入れた場合の効果
- [ ] 効果量の枠と枠上限
  - [ ] 他の連撃武器・バフと上限枠を共有するか、競合の確認 (バハ, コスモスBL, オメガ杖 闘争等)

例) DA2% と仮定し、1本  杖x10本で 計20% とした場合
- レゾナンス・スタッフ 2本で 40% ?
- 3本で60% となるか 枠上限50% 等の何らかの上限に引っかからないか。
  - 三手複数本の検証で 50%の小枠 上限があったはず

Motocal の現在の実装 DAのみ抜粋
```js
var normalNite = totals[key]["normalNite"] * totalSummon["zeus"];
var magnaNite = totals[key]["magnaNite"] * totalSummon["magna"];
var normalSante = totals[key]["normalSante"] * totalSummon["zeus"] + totals[key]["normalOtherSante"];
var magnaSante = totals[key]["magnaSante"] * totalSummon["magna"];
var exNite = Math.min(LIMIT.exDA, totals[key]["exNite"]);

var armDAupNormal = Math.min(LIMIT.normalDA, normalNite + normalSante);
var armDAupMagna = Math.min(LIMIT.magnaDA, magnaNite + magnaSante);
var armDAupBaha = Math.min(LIMIT.bahaDA, totals[key]["bahaDA"]);
var armDAupCosmos = Math.min(LIMIT.cosmosDA, totals[key]["cosmosBL"]);
var armDAupOther = Math.min(LIMIT.otherDA, totals[key]["DAOther"]); // 99999 for no limit

// unknown never reaches 50% of the current situation
var totalDA = 0.01 * totals[key]["baseDA"];
totalDA += 0.01 * totals[key]["LB"]["DA"];
totalDA += 0.01 * totals[key]["EXLB"]["DA"];
totalDA += buff["da"];
totalDA += totals[key]["DASupport"];
totalDA += totals[key]["DABuff"];
totalDA += totalSummon["da"];
totalDA += 0.01 * (armDAupNormal + armDAupMagna + exNite + armDAupBaha + armDAupCosmos + armDAupOther);
if (key == "Djeeta") {
    totalDA += buff["masterDA"];
    totalDA += buff["zenithDA"];
 }
```

- [ ] どの枠に加算されるのか / which DA/TA field get the amount

他、
- [ ] 確認項目: オメガ武器の連撃率upスキル は Motocal では未実装？

**Comment by kagekiyo7** [comment]
>確認項目: オメガ武器の連撃率upスキル は Motocal では未実装？

normalOtherSanteに加算されています。(加護が掛からない、DA,TA両方に適応)
```js
                                } else if (omegaType === "tousou") {
                                    totals[key]["normalOtherSante"] += skillAmounts["omega"][amount][slv - 1];
```

>どの枠に加算されるのか / which DA/TA field get the amount

normalOtherLesserSanteがいいのではないでしょうか(加護が掛からない、TAのみ適応)


----
上のソール･イコーリティ、上限枠追記しました。

**Comment by kei-gbf** [comment]
>> どの枠に加算されるのか / which DA/TA field get the amount

> 既存のnormalOtherLesserSante(加護が掛からない、TAのみ適応)、
> normalOtherNite(初期化だけ設定してある)に追加するといいと思います。

最終的に加算される枠は、上限を共有する枠になると思いますが、
(方陣枠, 通常枠でそれぞれ50%上限があったはずなので、枠検証は必要)

懸念があるのは、スキル効果の集計は
全員対象になる事から、キャラ個別の枠ではなくパーティ全体枠で集計可能になるんですよね。
１～６キャラ分を個別に計算 → 最適化すると１回の集計で済む。（効果量計算は個別）

また、効果量がスタックする場合、
聖域の錫杖 数量2 ではなく、２本別々に武器エントリーが作られた場合（例えば slv 違いなど)
スキル量集計のタイミングでは効果量を決定できず、キャラのダメージ個別に計算する時になる
辺りが現在の課題。

取り急ぎ、スキル量表示の問題もあるので、集計はジータちゃんの時にのみ行い、
集計後に纏めて適応するように、仮実装しました。#230

- "countEpic" エピックウェポンの数（全体共通）
- "countWant" 杖の数（全体共通）
- "numGrandEpic" エピック・グランドの本数（全体共通）
- "numResonanceStaff" レゾナンススタッフの本数（全体共通）
  - [ ] エピック・グランドがスタックする事から、仮で同様に実装しています。(要検証)

**Comment by kei-gbf** [comment]
game update, bug fix on resonance staff skill

![staff-update](https://user-images.githubusercontent.com/45387555/62771286-da04e680-bad7-11e9-8f13-3221d892437c.PNG)

**Comment by kei-gbf** [comment]
> スキル3つ重複の際
> エピックブランド・ゲインの効果量上限は80％かも
> https://twitter.com/mo_gati/status/1159282894122053632

the formula exactly matched, looks trust verification

- [x] ceil(ceil(20478 / 10) * 1.72 * 1.5) = 5284 ... expect 5284 epic 9 gain 2 (0.04 x 9 x 2)
- [x] ceil(ceil(23412 / 10) * __1.8__ * 1.5) = 6324 ... expected 6324 epic __9__ gain 3
- [x] ceil(ceil(23412 / 10) * __1.8__ * 1.5) = 6324 ... expected 6324 epic __6__ gain 3
- [x] ceil(ceil(23412 / 10) * 1.72 * 1.5) = 6043 ... expected 6043 epic 7 gain 3

epic 9 and 6 had same multiply thus the limitation is 1.8 (80%)

----

Resonance Staff

- https://twitter.com/desuko008/status/1159786626320494592
  - no MB, LB info
- https://twitter.com/tnyukkuri/status/1159775671423361025?s=21
  - DA確率に関して疑問

- [x] 14/150 ... TA: 約9.3% ok
- [ ] 25/150 ... DA: 約16.6% ... 母数からTAを引く必要は？
   25/(150-14) ...  約18.4%

Check points for the DA/TA verification

- [ ] MB
- [ ] LB / EXLB
- [ ] no Lancelot (DA support)

**Comment by kagekiyo7** [comment]
>スキル効果の集計

そこら辺の計算時の工程の流れは全くわからないのでおまかせします・・・。

>25/150 ... DA: 約16.6% ... 母数からTAを引く必要は？

正しくは DA: (100-9.3-3.0)%×(16.6-10)% = 5.7882% ですかね？(TAが出ない確率xDA率)
http://polnta.hatenablog.com/entry/2018/01/12/222040
https://kamigame.jp/%E3%82%B0%E3%83%A9%E3%83%96%E3%83%AB/%E3%82%B2%E3%83%BC%E3%83%A0%E7%9F%A5%E8%AD%98/%E3%82%B9%E3%82%AD%E3%83%AB-%E9%80%A3%E6%92%83.html

いずれにせよ約6%(1本辺り0.6%)なので問題はないかと。

**Comment by kagekiyo7** [comment]
いや、keiさんの求め方で合っている？

> DA率＝DA回数/(攻撃回数-TA回数)

https://twitter.com/konmatsuge/status/868322459929288704

**Comment by kei-gbf** [comment]
- 16.6 (25/150) は実際のDAが出た割合
- 基礎連撃率を乗算の前に引いてる部分、辺りが疑問点

自分の認識では
TAが出なかった確率(100-9.3%) x  DA率18.38% (25/(150-14)回) = 16.66% (25/150回) 実際にDAが出た割合
スキル計算で使われるのは、DA率＝DA回数/(攻撃回数-TA回数) になるはず。

**Comment by kagekiyo7** [comment]
新しい検証が出ました。

>DA1%/TA1%×杖本数(通常枠加算/上限50%)

https://twitter.com/Granblue_GW/status/1159979516799795200

**Comment by kagekiyo7** [comment]
第2スキルは1本目しか発動しないようです。

>Q.カーオン杖2本で連撃UPの加算量は倍になる？
>A.第2スキルは共存せず加算量は据え置き！

https://twitter.com/Granblue_GW/status/1160197206059565057

**Comment by kei-gbf** [comment]
ソール・イコーリティ スキル条件の確認
Confirmation for Absolute Equality skill conditions

![all-unique](https://user-images.githubusercontent.com/45387555/62835296-c2715d80-bc91-11e9-95e1-47b20ec19551.PNG)

ceil(ceil(53198/10)*1.2) = 6384 ... EX20% (*1.2) is enabled, they are all unique in the grid

- [x] Omega color different オメガ武器属性
- [x] JMP different colors ジョブ武器属性
- [x] Cosmos different types コスモス武器のタイプ違い
- [x] Xeno 4凸 is different weapon ゼノ武器の4凸
  - [x] 他の武器の凸違いは同じ武器扱い

**Comment by kei-gbf** [comment]
![epic2](https://user-images.githubusercontent.com/45387555/63236814-35726980-c27a-11e9-9f9c-168b7093057c.PNG)


- [x] ceil(ceil(45422/10)*1.4) = 6361
  - NOTE: the light-fist was 1凸, not get Grand Epic skill yet
- [ ] TODO: Grand epic and Heroic Tale/Absolute Equality share limit 80%? or individual ?

----
- [ ] Qilin Bow 's damage limit up was confirmed same field with 四象・邪

This is not new epic weapon. it's related we had the topic before.
I don't know the info source.

**Comment by kei-gbf** [comment]
EXの上限別枠を確認
Confirmed Heroic Tale/Absolute Equality EX stack on Epic Grand limit 80%

![ex80](https://user-images.githubusercontent.com/45387555/63448369-bbf49a00-c478-11e9-97c0-434b7ca5b0a2.PNG)

ceil(ceil(47698/10)*1.96) = 9359

96% := (Heroic Tale EX20% + Absolute Equality EX20% + Ex56% is Epic Grand x2 (8%) x 7 weapons)

- [ ] not confirmed yet, if the total limit had 100% or 120% etc
  - [ ] in actual the maximum is %120% ? (confirm)
    - the potential 10 weapons however
      currently there are no "gun", "katana", "music" types epic weapons
      0.12 x 7 = 0.84 ... then limit by 80%

I will try later when got Chains of Caucasus lv120

**Comment by kei-gbf** [comment]
![ex120](https://user-images.githubusercontent.com/45387555/63774034-593b4c80-c917-11e9-9632-d79eeac55dfe.PNG)

ceil(ceil(ceil(65600 / 10) * 2.2) * 1.10005) = 15878

- NOTE: it's NOT fair compare, my crew had got boost dark ATK 10% (* almost 1.1)
- [x] 2.2 ... confirmed it's 120% up
  Grand Epic limit EX80% + EX20% + EX20% stack and no total limit

**Comment by kei-gbf** [comment]
Implemented #328
