### ISSUE TITLE
Update patch 2020 Jan/Feb/Mar

### ISSUE THREAD

**Issue by kei-gbf** [MotocalDevelopers/motocal#407]
- [ ] 2020-03-03
  - [ ] add new weapon [Sol Remnant](https://gbf.wiki/Sol_Remnant)
  - [ ] add new weapon [Fateless](https://gbf.wiki/Fateless)
  - [ ] add new weapon [Yggdrasil's_Bough](https://gbf.wiki/Yggdrasil%27s_Bough)
  - [ ] add new weapon [Innocent Love](https://gbf.wiki/Innocent_Love)
  - [ ] add new weapon [Rhongomyniad](https://gbf.wiki/Rhongomyniad)
  - [ ] add new weapon [Claws of Terror](https://gbf.wiki/Claws_of_Terror)
- [ ] 2020-02-29
  - [ ] add new chara [Lecia_(Water)](https://gbf.wiki/Lecia_(Water))
  - [ ] add new chara [Vania and Malinda](https://gbf.wiki/Vania_and_Malinda)
  - [ ] add new chara [Rei](https://gbf.wiki/Rei)
  - [ ] add new weapon [Commander's_Sidearm](https://gbf.wiki/Commander%27s_Sidearm)
  - [ ] add new weapon [Plushie Pal](https://gbf.wiki/Plushie_Pal)
  - [ ] add new weapon [Sunya](https://gbf.wiki/Sunya)
- [ ] 2020-02-26
  - [ ] add new weapon [Honoikazuchi no Okami](https://gbf.wiki/Honoikazuchi-no-Okami)
  - [ ] uncap weapon [SHRIMP Spreader](https://gbf.wiki/SHRIMP_Spreader)
- [ ] 2020-02-14
  - [ ] add new chara [Scathacha (Valentine)](https://gbf.wiki/Scathacha_(Valentine))
  - [ ] add new chara [Grimnir (Valentine)](https://gbf.wiki/Grimnir_(Valentine))
  - [ ] add new weapon [Deirdre's_Heart](https://gbf.wiki/Deirdre%27s_Heart)
  - [ ] add new weapon [Lupercalia](https://gbf.wiki/Lupercalia)
- [ ] 2020-02-10
  - [ ] uncap chara [Tiamat](https://gbf.wiki/Tiamat)
  - [ ] uncap weapon [Gottfried](https://gbf.wiki/Gottfried)
  - [ ] uncap weapon [Ancient Bandages](https://gbf.wiki/Ancient_Bandages)
  - [ ] uncap weapon [Full Metal Recoil](https://gbf.wiki/Full_Metal_Recoil)
  - [ ] uncap weapon [Bloody Scar](https://gbf.wiki/Bloody_Scar)
  - [ ] uncap weapon [Gangsta Knife](https://gbf.wiki/Gangsta_Knife)
  - [ ] uncap weapon [Another Sky](https://gbf.wiki/Another_Sky)
- [ ] 2020-01-31
  - [ ] add new chara [Yodarha (Wind)](https://gbf.wiki/Yodarha_(Wind))
  - [ ] add new chara [Ilsa (Light)](https://gbf.wiki/Ilsa_(Light))
  - [ ] add new weapon [True Tiger's Bane](https://gbf.wiki/True_Tiger%27s_Bane)
  - [ ] add new weapon [Takeminakata](https://gbf.wiki/Takeminakata)
- [ ] 2020-01-28
  - [ ] uncap chara [Zeta](https://gbf.wiki/Zeta)
  - [ ] add new weapon [Plasma Ripper](https://gbf.wiki/Plasma_Ripper)
- [ ] 2020-01-22
  - [ ] uncap chara [makira](https://gbf.wiki/Mahira)

※ リンクは英語wiki、"Extra Data" タブより各攻略サイトへのリンクがあります。

----
# Task list
- [x] 作業一覧の書き出し
  - [en wiki](https://gbf.wiki/News_2020) より抜粋
- [ ] PR 作成
  - [ ] 2020-01/22,28: 上限解放キャラx2 + 新武器
  - [ ] 2020-01-31 
  - [ ] 2020-02-10 上限解放
  - [ ] 2020-02-14 バレンタイン
  - [ ] 2020-02/26,29
  - [ ] 2020-03-03 アストラル武器
    - [ ] 武器フィルター #331 へ新カテゴリ追加

時間が出来たので、周年辺りを目途に少しづつ進めていきます。
この Issue は情報纏めやロードマップ＆進捗管理として、PRは個別に作成する予定です。

後、[キャラ・武器追加パッチの作り方](https://github.com/MotocalDevelopers/motocal/wiki/%E3%82%AD%E3%83%A3%E3%83%A9%E3%83%BB%E6%AD%A6%E5%99%A8%E8%BF%BD%E5%8A%A0%E3%83%91%E3%83%83%E3%83%81%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9)
まとめてるので、パッチ作成作業の注意点（READMEには書かれてなかった事など）あれば追記していきます。

**Comment by kei-gbf** [comment]
仮で上記パッチを適応したものを kei-gbf/build-2020_03_08 にまとめておきます。
(merge 順序は #403, #406 ～) 

- [ ] min HP/ATK は抜けが多かったため、wikiを参考に手入力しました
- [ ] 武器スキルが適応されているか～等は未検査
- [ ] キャラ サポアビも未調査

----
他、未対応項目 (TODO)

- キャラ固有奥義減衰・倍率
  - [ ] 水キャラ2体。サポアビとして実装？
- エビスプレッダー 第二スキル
  - [ ] → 進境と同じように、最大時の効果で実装？
- アストラル武器 第二スキル
  - [ ] メイン装備時
  - [ ] 条件次第で効果量累積は、対応可

**Comment by Groovman** [comment]
>   * [ ]  キャラの上限解放 (HELP wanted)
>     
>     * [ ]  How to make uncap chara data?

You update the csv data, by comparing the current data and the update.
Most often it is just changing the picture id number to a 3 at the end, added weapon profs to it and updating the max atk and hp data.
